# Generated by Django 5.1.7 on 2025-03-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
    ]
