# Generated by Django 5.1.7 on 2025-03-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_banner_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
